### PR TITLE
Filtering of quads in SimpleQuadStore

### PR DESCRIPTION
**Pull request by cordawyn**
Hi! I've implemented filtering for `SimpleQuadStore.getQuads()`, which was causing invalid behaviour in `Initializer.getAllTriplesMaps()` (and others), when `SimpleQuadStore` is used as the backend store, instead of `RDF4JStore`.

`SimpleQuadStore` is a default option and it works faster for me than `RDF4JStore`, so... here you go 😄

### CODE REVIEW

**Comment by pheyvaer** [comment]
Hi @cordawyn 

Thanks for the PR! What invalid behaviour were you experiencing?

**Comment by cordawyn** [comment]
@pheyvaer You can see a couple of invocations of `rmlStore.getQuads()` with arguments assuming that not *all* triples are returned. Specifically, check out the second one, that should get the triple maps – you check that the result `isEmpty()` and only then add the map to `temp`... which never happens, if you always return all triples 😄 
With that, I'm always getting "No Triples Maps found. The mapping document you should at least have one Triples Map." exception if `SimpleQuadStore` is used.

**Comment by pheyvaer** [comment]
Thanks! We will add it to the next release.

**Comment by pheyvaer** [comment]
Hi @cordawyn, [a new release](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.3.1) is now available that includes your changes. Thanks again for the help!

**Pull request closed without merging**
