### PR TITLE
Add test case for referencing the relative JSONPath (@)

### PR DESCRIPTION
**Pull request by vemonet**
Related to the issue discussed in pull request https://github.com/kg-construct/mapping-challenges/pull/33 and issue https://github.com/RMLio/rmlmapper-java/issues/95

I used those YARRRML mappings to generate the RML using Matey:

```yaml
prefixes:
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  ex: "http://example.com/"
mappings:
  ingredients:
    sources:
      - ['data.json~jsonpath', "$.[*].ingredients[*]"]
    s: ex:$(@)
    po:
      - [rdfs:label, $(@)]
      
  recipes:
    sources:
      - ['data.json~jsonpath', "$.[*]"]
    s: ex:$(id)
    po:
      - [ex:ingredients, ex:$(ingredients)~iri]
```

### CODE REVIEW

**Comment by pheyvaer** [comment]
@vemonet Thanks! We're having a look at it.

**Comment by pheyvaer** [comment]
@vemonet Regarding the output, the `output.nq` has IRIs as objects for the predicate `ex:ingredients`, but in YARRRML you define it as a Literal. What exactly do you expect?

**Comment by vemonet** [comment]
@pheyvaer indeed, I fixed the mappings to use an IRI

**Comment by pheyvaer** [comment]
@vemonet These test case have been included and succeed in the latest release. 😄

**Pull request closed without merging**
